name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci --prefix chrono-cycle

      - name: Lint
        run: npm run lint --prefix chrono-cycle
